; STANDARD HEADER FILE
	PROCESSOR		16F876A
;---REGISTER FILES 선언 ---
;  BANK 0
INDF	 EQU	00H
TMR0	 EQU	01H
PCL	 EQU	02H
STATUS	 EQU	03H
FSR	 EQU	04H	
PORTA	 EQU	05H
PORTB	 EQU	06H
PORTC	 EQU	07H
EEDATA	 EQU	08H
EEADR	 EQU	09H
PCLATH	 EQU	0AH
INTCON	 EQU	0BH
; BANK 1
OPTIONR	 EQU	81H
TRISA	 EQU	85H
TRISB	 EQU	86H
TRISC	 EQU	87H
EECON1	 EQU	88H
EECON2	 EQU	89H
ADCON1	 EQU	9FH
;---STATUS BITS 선언---
IRP	 EQU	7
RP1	 EQU	6
RP0	 EQU	5
NOT_TO 	 EQU	4
NOT_PD 	 EQU	3
ZF 	 EQU	2 ;ZERO FLAG BIT
DC 	 EQU	1 ;DIGIT CARRY/BORROW BIT
CF 	 EQU	0 ;CARRY BORROW FLAG BIT

; -- INTCON BITS 선언 --
; -- OPTION BITS 선언 --

W 	 EQU	B'0' ; W 변수를 0으로 선언
F 	 EQU	.1   ; F 변수를 1로 선언

; --USER
DISP1	 EQU 	20H
DBUF1	 EQU  	21H
DBUF2	 EQU	22H
DISP2	 EQU	23H
W_TEMP	 EQU	24H
STATUS_TEMP EQU	25H
HOHO	 EQU	26H
MUTEX	 EQU	27H
INT_CNT	 EQU	28H
D_1SEC	 EQU	29H
D_10SEC	 EQU	30H
D_1MIN	 EQU	31H
D_10MIN	 EQU	32H
;SWSW	 EQU	33H  
;DCDC	 EQU 	34H
SORS	 EQU	35H
TEMP	 EQU	36H
TEMP2	 EQU	37H
STOP	 EQU	38H
RMB	 EQU	39H ; 다운카운터 1분 횟수 저장하는 레지스터
SORS2	 EQU 	40H
;MAIN PROGRAM
	ORG 	0000	
	GOTO	START_UP
	ORG	4
;-------------------INT/TIMER -------------------
	MOVWF	W_TEMP	
	SWAPF	STATUS,W
	MOVWF	STATUS_TEMP

	GOTO	DISP	;DISPLAY 부 프로그램

BACK	SWAPF	STATUS_TEMP,W ; 저장된 내용으로 복원
	MOVWF	STATUS
	SWAPF	W_TEMP,F
	SWAPF	W_TEMP,W
	BCF	INTCON,2
	RETFIE

	
;DISPLAY ROUTINE
DISP
	BTFSS	HOHO,1
	GOTO	HOTEST
	BTFSS	HOHO,0
	GOTO	O_MIN;	2 10
	GOTO	T_MIN;	3 11

HOTEST	BTFSS	HOHO,0
	GOTO	O_SEC;	0 00
	GOTO	T_SEC;	1 01
	
T_MIN
; D_10MIN 변수 내용이 MSD 7-segment에 표시되도록 할 것			
	
	CALL	ALLOFF
	MOVF	D_10MIN,W	;10MIN을 7SEGMENT에  출력
	CALL	CONV
	CALL	PRINT
	BCF	PORTA,3 ;DG1에 출력
	INCF	HOHO,F
	GOTO	BACK

O_MIN	
; D_1MIN 변수 내용이 MSD 7-segment에 표시되도록 할 것			
	
	CALL 	ALLOFF
	MOVF	D_1MIN,W	;1MIN을 7SEGMENT에  출력
	CALL	CONV
	IORLW	B'00000001'
	CALL	PRINT
	BCF	PORTA,2 ;DG2에 출력
	INCF	HOHO,F
	GOTO	BACK
	
T_SEC
; D_10SEC 변수 내용이 MSD 7-segment에 표시되도록 할 것			
	CALL	ALLOFF
	MOVF	D_10SEC,W	;10SEC을 7SEGMENT에  출력
	CALL	CONV
	CALL 	PRINT
	BCF	PORTB,2 ;DG3에 출력
	INCF	HOHO,F
	GOTO	BACK
	
O_SEC
; D_1SEC 변수 내용이 MSD 7-segment에 표시되도록 할 것
	CALL 	ALLOFF
	MOVF	D_1SEC,W	;1SEC을  7SEGMENT에  출력
	CALL	CONV
	CALL	PRINT
	BCF	PORTB,1 ;DG4에 출력
	INCF	HOHO,F
	INCF	INT_CNT,F
	GOTO	BACK
;--------------------세팅-------------------------
START_UP	
	BSF	STATUS,RP0
	MOVLW	B'00000010' ; 2.048msec 고쳐야함!!!!
	MOVWF 	OPTIONR
	MOVLW	B'00011000'
	MOVWF	TRISC
	MOVLW	B'11100000'
	MOVWF	TRISA
	MOVLW	B'01111000'
	MOVWF	TRISB
	MOVLW	B'00000111'
	MOVWF	ADCON1
	BCF	STATUS,RP0 ; 뺑크 00
	MOVLW	B'00000000'
	MOVWF	HOHO
	MOVWF	INT_CNT
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	MOVWF	D_10MIN
	MOVWF	D_1MIN	
	MOVWF	SORS
	MOVWF	SORS2
	BCF	PORTB,7
	GOTO	ST

;-------------------SUBROUTINE-------------------	

DELAY	;5ms DELAY
	MOVLW	.125
	MOVWF	DBUF1
LOOP1	MOVLW	.10	
	MOVWF	DBUF2
LOOP2	NOP
	DECFSZ	DBUF2,F
	GOTO	LOOP2
	DECFSZ	DBUF1,F
	GOTO	LOOP1
	RETURN


DELAY_1	;0.25 sec DELAY
	MOVLW	.250
	MOVWF	DBUF1
LOOP4	MOVLW	.250	
	MOVWF	DBUF2
LOOP3	NOP
	DECFSZ	DBUF2,F
	GOTO	LOOP3
	DECFSZ	DBUF1,F
	GOTO	LOOP4
	RETURN
	
	
CONV	;LOOKUPTABLE
	ANDLW	0FH
	ADDWF	PCL,F
	; 765102!)
	RETLW	B'11111100' ;0
	RETLW	B'01100000' ;1
	RETLW	B'11001110' ;2
	RETLW	B'11101010' ;3
	RETLW	B'01110010' ;4
	RETLW	B'10111010' ;5
	RETLW	B'10111110' ;6
	RETLW	B'11110000' ;7
	RETLW	B'11111110' ;8
	RETLW	B'11111010' ;9
	RETLW	B'00000010' ;-
	RETLW	B'11111100' ;0
	RETLW	B'11111100' ;0
	RETLW	B'11111100' ;0
	RETLW	B'11111100' ;0
	RETLW	B'11111100' ;0
	RETLW	B'11111100' ;0


ALLOFF
	BCF	PORTC,7		;전부 OFF	
	BCF	PORTC,6
	BCF	PORTC,5
	BCF	PORTC,2
	BCF	PORTC,1
	BCF	PORTC,0
	BCF	PORTA,0
	BCF	PORTA,1
	BSF	PORTA,3		;디짓선택 초기화
	BSF	PORTA,2
	BSF	PORTB,2
	BSF	PORTB,1	
	RETURN


PRINT	
	MOVWF	TEMP
	MOVLW	B'11100000'
	MOVWF	PORTC
	MOVF		TEMP,W
	ANDWF	PORTC,F
	MOVLW	B'00011100'
	MOVWF	TEMP2
	MOVF		TEMP,W
	ANDWF	TEMP2,F
	RRF		TEMP2
	RRF		TEMP2
	MOVF		TEMP2,W
	IORWF		PORTC,F
	MOVLW	B'00000011'
	MOVWF	TEMP2
	MOVF		TEMP,W
	ANDWF	TEMP2,W
	IORWF		PORTA,F ; 7SEG부분 완료
	RETURN
	
TIMERMODE 
	CALL	O_SEC_RESET
	CALL	T_SEC_RESET
	RETURN

O_SEC_RESET
	MOVLW	.9
	MOVWF	D_1SEC
	RETURN

T_SEC_RESET
	MOVLW	.5
	MOVWF	D_10SEC
	RETURN


MANDOO	DECF	D_10MIN
	MOVLW	.9
	MOVWF	D_1MIN
	RETURN

;--------------------MAINPROGRAM--------------------
	
	

ST	BSF	INTCON,5 ; TIMER INTERRUPT ENABLE
	BSF	INTCON,7 ; GOLBAL INT. ENABLE

DEFAULT	
	BTFSS	PORTB,4	;스위치 2확인 , 스탑워치 ㄱㄱ 
	GOTO	SWT
	BTFSS	PORTB,5 ; 스위치 3확인, 타이머 ㄱㄱ
	GOTO	TMT
	CLRF	INT_CNT ; 이거 꼭 유념하기 ! 계속 계수를 하면서 인트카운트가 증가되면 노답임 스탑워치랑 타이머 시작할때
	GOTO	DEFAULT

SWT
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	BTFSS	PORTB,5	;3확인 
	GOTO	MUTE	;둘다 눌렀으면 뮤트
	BTFSS	PORTB,4	;2다시확인  0.25초 정도 누르면 스탑워치 시작 
	GOTO	STOPWATCH
	GOTO	DEFAULT


TMT
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	CALL	DELAY_1
	BTFSS	PORTB,4
	GOTO	MUTE	;둘다 눌렀으면 뮤트 
	BTFSS	PORTB,5	;3다시확인 0.25초 정도 누르면 타이머 시작
	GOTO	TIMER
	GOTO	DEFAULT


;-------------------기능1 스탑워치---------------------	
	
STOPWATCH
	MOVLW	.0
	MOVWF	D_10MIN
	MOVWF	D_1MIN
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	MOVWF	INT_CNT

	

GOGOGO	
	BTFSS	PORTB,4  ; SW2  눌러졌으면 스톱워치 리셋으로 분기 
	GOTO	SWRESET ; STOPWATCH RESET
	BTFSS	PORTB,5 ; SW3 눌러졌으면 라멘으로 분기, 아니면 
	GOTO	RAMEN	; M루프 감
	GOTO	M_LOOP
RAMEN
	BTFSS	PORTB,4  ; SW2도 눌러졌으면 디폴트로 분기
	GOTO	DEFAULT
	CALL	DELAY_1
	BTFSS	PORTB,5 ; SW3 눌러졌으면 START STOP, 안눌러졌으면 계속 확인 
	INCF	SORS
	GOTO	M_LOOP


M_LOOP
	
	BTFSS	SORS,0	; 스타트 스탑 체크
	GOTO 	GOGOGO ; 스탑이면 안가고 스타트면 간다
	
	MOVLW	.122 ; 이후에 계수
	SUBWF	INT_CNT,W
	BTFSS	STATUS,ZF
	GOTO	GOGOGO
; 1초마다 들어오는 부분


	CLRF	INT_CNT ; 다음 1초를 기다리기 위한 초기화
	INCF	D_1SEC ; 1초 단위 변수 증가
	MOVLW	.10
	SUBWF	D_1SEC,W
	BTFSS	STATUS,ZF
	GOTO	GOGOGO

; 10초마다 들어오는 부분
	CLRF	D_1SEC ; 다음 10초를 기다리기 위한 초기화
	INCF	D_10SEC ; 10초단위 변수 증가
	MOVLW	.6
	SUBWF	D_10SEC,W
	BTFSS	STATUS,ZF
	GOTO	GOGOGO
 	
 ; 1분마다 들어오는 부분
 	CLRF	D_1SEC
 	CLRF	D_10SEC ;  초 리셋 ^^
 	INCF	D_1MIN
 	MOVLW	.10
 	SUBWF	D_1MIN,W
 	BTFSS	STATUS,ZF
 	GOTO	GOGOGO
 
 ; 10분마다 들어오는 부분
 
 	CLRF	D_1SEC
 	CLRF	D_10SEC
 	CLRF	D_1MIN
 	INCF	D_10MIN
 	MOVLW	.10
 	SUBWF	D_10MIN,W
 	BTFSC	STATUS,ZF
 	GOTO	SWRESET
 	GOTO	GOGOGO
 


	
SWRESET	BTFSS	PORTB,5 ;두개다 눌러졌으면 디폴트
	GOTO	DEFAULT
	MOVLW	B'00000000'
	MOVWF	HOHO
	MOVWF	INT_CNT
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	MOVWF	D_10MIN
	MOVWF	D_1MIN;SW RESET
	MOVWF	SORS
	GOTO	STOPWATCH 	; 리셋만 눌렀으면 다시 스탑워치로 분기
	

;--------------------기능2 타이머/알람------------------------
TIMER	
	MOVLW	.0
	MOVWF	D_10MIN
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	MOVWF	INT_CNT
	MOVLW	0FFH
	MOVWF	D_1MIN
	INCF	SORS2

GOGOGO2	
	BTFSS	PORTB,4  ; SW2 누르면 1분씩 추가하는 셋타임으로 분기
	GOTO	SETTIME
	BTFSS	PORTB,5 ; SW3 눌러졌으면 START STOP 확인하는 점보로 분기, 안눌러졌으면 계속 확인 
	GOTO	JUMBO
	GOTO	MM_LOOP
	
JUMBO
	BTFSS	PORTB,4  ; 둘다 눌러졌으면 디폴트 
	GOTO	DEFAULT
	CALL	DELAY_1
	BTFSS	PORTB,5 ; SW3 눌러졌으면 START STOP, 안눌러졌으면 계속 확인 
	INCF	SORS2

MM_LOOP
; interrupt가 들어온 횟수 확인 (시간 계수) 

	BTFSS	SORS2,0 ; START STOP 맞는지 확인
	GOTO 	GOGOGO2  

	
 ;-----------시간종료 확인하는 부분-------------
 	MOVLW	.0
	SUBWF	D_10MIN,W
	BTFSS	STATUS, ZF
	GOTO	GOGOGO3	
	MOVLW	.0
	SUBWF	D_1MIN,W
	BTFSS	STATUS, ZF
	GOTO	GOGOGO3
	MOVLW	.0
	SUBWF	D_10SEC,W
	BTFSS	STATUS, ZF
	GOTO	GOGOGO3
	MOVLW	.0
	SUBWF	D_1SEC,W
	BTFSS	STATUS, ZF
	GOTO	GOGOGO3
	GOTO	RINGMYBELL; 0000이면 링마벨 
;-----------------------------------------
			
GOGOGO3		 	
	

	BTFSS	PORTB,5 ; 동작중 스위치 3 눌러졌으면 고고고2 가서 스위치 쳌 
	GOTO	GOGOGO2

	MOVLW	.122
	SUBWF	INT_CNT,W
	BTFSS	STATUS,ZF
	GOTO	GOGOGO2
; 1초마다 들어오는 부분 

CK_LOOP
	CLRF	INT_CNT ; 다음 1초를 기다리기 위한 초기화
	DECF	D_1SEC ; 1초 단위 변수 감
	MOVLW	0FFH
	SUBWF	D_1SEC,W
	BTFSS	STATUS,ZF
	GOTO	MM_LOOP

; 10초마다 들어오는 부분
	CALL	O_SEC_RESET  ;1초에 9
	DECF	D_10SEC ; 10초단위 변수 감소
	MOVLW	0FFH
	SUBWF	D_10SEC,W
	BTFSS	STATUS,ZF
	GOTO	MM_LOOP
 	
 ; 1분마다 들어오는 부분
 	CALL	TIMERMODE ; 1초에 9, 10초에 5넣음
 	DECF	D_1MIN
 	MOVLW	0FFH
	SUBWF	D_1MIN,W
	BTFSS	STATUS,ZF
 	GOTO	MM_LOOP
 
 ; 10분마다 들어오는 부분
 	CALL 	TIMERMODE ; 1초에 9, 10초에 5넣음
	DECF	D_10MIN
 	GOTO	MM_LOOP
 
	
 
	
SETTIME
	BTFSS	PORTB,5 ;스위치 3까지 둘다 눌렀으면 디폴트
	GOTO	DEFAULT
	CALL	DELAY_1
	;50ms 마다 1씩 증가 ^^ 
	CALL	TIMERMODE
	INCF	D_1MIN
	MOVLW	.10
	SUBWF	D_1MIN,W		;10분이상 ++됐으면 D_10MIN ++
	BTFSS	STATUS,ZF
	GOTO	GOGOGO2
	CLRF	D_1MIN
	INCF	D_10MIN
	MOVLW	.10		;100분이상 ++됐으면 1MIN,10MIN CLEAR
	SUBWF	D_10MIN,W
	BTFSS	STATUS,ZF
	GOTO 	GOGOGO2
	CLRF	D_1MIN
	CLRF	D_10MIN
	GOTO	GOGOGO2	
	
RINGMYBELL

	BTFSC	MUTEX, 0 ; 무음모드일때 스윙마베이베	
	GOTO 	SWINGMYBABY
	
	BCF	PORTA,4
	CALL	DELAY_1
	BSF	PORTA,4

	CALL	DELAY_1
	
	BCF	PORTA,4
	CALL	DELAY_1
	BSF	PORTA,4

	CALL	DELAY_1
	
	BCF	PORTA,4
	CALL	DELAY_1
	BSF	PORTA,4
	GOTO	DEFAULT; 합치면 디폴트로 ㄱㄱ 

SWINGMYBABY ; ---- 출력
	MOVLW	.10
	MOVWF	D_10MIN
	MOVWF	D_1MIN
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	GOTO	DEFAULT

;--------------------기능3 무음/ 유음---------------------	

MUTE	INCF	MUTEX,F ;1일때 무음모드
	BTFSC	MUTEX,0 
	GOTO	SILENT  ; 
	BCF	PORTA,4
	CALL	DELAY_1
	BSF	PORTA,4
	
	MOVLW	.0
	MOVWF	D_10MIN
	MOVWF	D_1MIN
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	GOTO	DEFAULT
	GOTO	DEFAULT	
	
SILENT	MOVLW	.10
	MOVWF	D_10MIN
	MOVWF	D_1MIN
	MOVWF	D_10SEC
	MOVWF	D_1SEC
	GOTO	DEFAULT

END
	
	